# Generated by Django 4.1.2 on 2023-06-24 12:04

from django.db import migrations, models
import tallerMecanico.models


class Migration(migrations.Migration):

    dependencies = [
        ('tallerMecanico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(upload_to=tallerMecanico.models.imagen)),
            ],
        ),
    ]
